volumes:
  postgres-data:
    name: postgres-data
    driver: local

networks:
  food-crud:
    name: food-crud


services:
  db:
    image: postgres:16.6
    restart: always
    container_name: postgres-test
    environment:
      POSTGRES_DB: postgres       
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PASSWORD}
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - food-crud
    volumes:
      - postgres-data:/var/lib/postgresql/data
